# An example configuration

region: us-east-1
memorySize: 1024
stage: dev

# Both these buckets will be created
source_bucket: gsieling-video-bucket
destination_bucket: gsieling-images-bucket

# This will transcode audio into hls format
ffmpeg_params: "-hide_banner -vf fps=5"
