AWSTemplateFormatVersion: "2010-09-09"

Description: Video uploader

#Parameters:
#  FilePath:
#    Description: The path of the  file.
#    Type: String
#    Default: /home/ec2-user/userdata

Resources:
  UserPool:
    Type: "AWS::Cognito::UserPool"
      
  VideoBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins: 
              - "*"
            AllowedMethods: 
              - POST
              - GET
              - PUT
              - DELETE
              - HEAD
            AllowedHeaders: 
              - "*"

  # TODO upload gatsby site
  # TODO cloudfront this
  WebsiteBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref WebsiteLogsBucket
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref WebsiteBucket
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: "WebsiteBucket"
                  - "/*"
            Principal: "*"

  # TODO hook up logs
  WebsiteLogsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: LogDeliveryWrite

Outputs:
  WebsiteBucketUrl:
    Description: Website Bucket Url
    Value: !GetAtt WebsiteBucket.WebsiteURL

  VideoBucketArn:
    Description: Video storage bucket
    Value: !GetAtt VideoBucket.Arn

  UserPoolName:
    Description: User Pool
    Value: !GetAtt UserPool.ProviderName
    
  UserPoolUrl:
    Description: User Pool Url
    Value: !GetAtt UserPool.ProviderURL

