AWSTemplateFormatVersion: "2010-09-09"

Description: Video uploader

#Parameters:
#  FilePath:
#    Description: The path of the  file.
#    Type: String
#    Default: /home/ec2-user/userdata

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins: 
              - "*"
            AllowedMethods: 
              - POST
              - GET
              - PUT
              - DELETE
              - HEAD
            AllowedHeaders: 
              - "*"

Outputs:
  BucketName:
    Description: Video storage bucket
    Value: !GetAtt S3Bucket.Arn
